"""
Enhanced Document Generation System with LangChain Integration

This module provides a comprehensive document generation system that:
1. Integrates with LangChain as a tool
2. Uses the existing DocumentWriter utility
3. Supports multiple formats (PDF, DOCX, PPTX, TXT)
4. Provides enhanced formatting and templates
5. Is refactored into reusable classes
"""

from typing import Dict, Any, Optional
from pathlib import Path
from datetime import datetime
from langchain_core.tools import tool
from pydantic import BaseModel, Field
import json

# Import your existing document writer
from langchain_tools.document_exporter.doc_writer import DocumentWriter


class DocumentConfig(BaseModel):
    """Configuration for document generation"""
    content: str = Field(..., description="The content to be written to the document")
    document_type: str = Field(default="pdf", description="Type of document: pdf, docx, pptx, txt")
    title: Optional[str] = Field(default=None, description="Document title")
    template: str

class DocumentTemplate:
    """Document templates for different content types"""
    
    @staticmethod
    def quiz_template(content: str, title: str = "Quiz") -> str:
        """Format content as a quiz document"""
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        # Add instructions for quiz
        instructions = """INSTRUCTIONS:
1. Read each question carefully
2. Choose the best answer for multiple choice questions
3. Write your answers clearly in the space provided
4. Attempt all questions
5. Time allowed: As specified by instructor

"""
        
        formatted_content = f"""
**{title.center(60)}**

Date: {timestamp}

{instructions}
{content}

Good Luck!
"""
        return formatted_content
    
    @staticmethod
    def report_template(content: str, title: str = "Report") -> str:
        """Format content as a report document"""
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        formatted_content = f"""
**{title.upper().center(60)}**

Date: {timestamp}

EXECUTIVE SUMMARY

{content[:200]}...

DETAILED CONTENT

{content}

CONCLUSION

This report provides comprehensive information on the requested topic.

Generated automatically by SME Assistant
"""
        return formatted_content
    
    @staticmethod
    def default_template(content: str, title: str = "Document") -> str:
        """Default document template"""
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        formatted_content = f"""
**{title.center(60)}**

Generated: {timestamp}

{content}

Generated by SME Assistant
"""
        return formatted_content


class EnhancedDocumentGenerator:
    """
    Enhanced document generator that integrates with existing DocumentWriter
    and provides additional features like templates and better formatting
    """
    
    def __init__(self, base_output_dir: str = "generated_documents"):
        self.base_output_dir = Path(base_output_dir)
        self.base_output_dir.mkdir(parents=True, exist_ok=True)
        
        # Template mapping
        self.templates = {
            "quiz": DocumentTemplate.quiz_template,
            "report": DocumentTemplate.report_template,
            "default": DocumentTemplate.default_template
        }
    
    def _format_quiz_content(self, content: str) -> str:
        """
        Format quiz content to ensure proper MCQ option formatting
        """
        lines = content.split('\n')
        formatted_lines = []
        
        for line in lines:
            line = line.strip()
            if not line:
                formatted_lines.append('')
                continue
                
            # Check if line contains MCQ options (a), b), c), d) or A), B), C), D)
            if any(line.startswith(f'{opt})') for opt in ['a', 'b', 'c', 'd', 'A', 'B', 'C', 'D']):
                # Ensure MCQ options are properly formatted and on separate lines
                formatted_lines.append(line)
            elif ' a)' in line or ' A)' in line:
                # Split options that might be on the same line
                parts = line.split(' ')
                current_part = []
                for part in parts:
                    if any(part.startswith(f'{opt})') for opt in ['a)', 'b)', 'c)', 'd)', 'A)', 'B)', 'C)', 'D)']):
                        if current_part:
                            formatted_lines.append(' '.join(current_part))
                            current_part = []
                        current_part.append(part)
                    else:
                        current_part.append(part)
                if current_part:
                    formatted_lines.append(' '.join(current_part))
            else:
                formatted_lines.append(line)
        
        return '\n'.join(formatted_lines)
    
    def generate_document(self, config: DocumentConfig) -> Dict[str, Any]:
        """
        Generate a document based on the provided configuration
        
        Args:
            config: DocumentConfig object with all generation parameters
            
        Returns:
            Dict with generation results including file path, success status, etc.
        """
        try:
            # Format content if it's a quiz
            content_to_use = config.content
            if config.template == "quiz":
                content_to_use = self._format_quiz_content(config.content)
            
            # Prepare content with template
            template_func = self.templates.get(config.template, self.templates["default"])
            formatted_content = template_func(
                content=content_to_use,
                title=config.title or "Generated Document",
            )
            
            
            output_dir = self.base_output_dir
            output_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate filename
            safe_title = self._sanitize_filename(config.title or "document")
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            base_name = f"{safe_title}_{timestamp}"
            
            # Generate the document using existing DocumentWriter
            file_path = DocumentWriter.write(
                content=formatted_content,
                file_type=config.document_type,
                output_dir=str(output_dir),
                base_name=base_name
            )
            
            # Calculate relative path for return
            try:
                relative_path = Path(file_path).relative_to(Path.cwd())
            except ValueError:
                # If relative path calculation fails, use the file path as is
                relative_path = Path(file_path)
            
            return {
                "success": True,
                "file_path": str(file_path),
                "relative_path": str(relative_path),
                "filename": Path(file_path).name,
                "document_type": config.document_type,
                "title": config.title,
                "size_bytes": Path(file_path).stat().st_size if Path(file_path).exists() else 0,
                "message": f"Document '{Path(file_path).name}' generated successfully"
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e),
                "message": f"Failed to generate document: {str(e)}"
            }
    
    def generate_quiz_document(self, quiz_content: str, quiz_params: Dict[str, Any]) -> Dict[str, Any]:
        """
        Specialized method for generating quiz documents
        
        Args:
            quiz_content: The quiz content/questions
            quiz_params: Quiz parameters (difficulty, topic, etc.)
            
        Returns:
            Dict with generation results
        """
        # Extract information from quiz parameters
        topic = quiz_params.get('topic', 'General Knowledge')
        difficulty = quiz_params.get('difficulty', 'medium')
        question_type = quiz_params.get('question_type', 'mcq')
        export_info = quiz_params.get('export_info', {})
        
        # Create title
        title = f"{topic.title()} Quiz - {difficulty.title()} Level"
        
        # Determine document type from export info
        doc_type = export_info.get('export_format', 'pdf')
        
        # Create configuration
        config = DocumentConfig(
            content=quiz_content,
            document_type=doc_type,
            title=title,
            template="quiz"
        )
        
        return self.generate_document(config)
    
    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename to remove invalid characters"""
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, '_')
        return filename[:50]  # Limit length
    
    def list_generated_documents(self) -> list:
        """List all generated documents"""
        documents = []
        for file_path in self.base_output_dir.rglob('*'):
            if file_path.is_file():
                documents.append({
                    "filename": file_path.name,
                    "path": str(file_path),
                    "size": file_path.stat().st_size,
                    "created": datetime.fromtimestamp(file_path.stat().st_ctime).isoformat()
                })
        return documents


# Initialize the global generator instance
document_generator = EnhancedDocumentGenerator()


# LangChain Tool Wrapper
@tool
def enhanced_document_tool(
    content: str,
    document_type: str = "pdf",
    title: str = "Generated Document",
    template: str = "default",
    filename: str = None
) -> str:
    """
    Generate a document using the enhanced document generation system.
    
    Args:
        content: The text content to include in the document
        document_type: Type of document (pdf, docx, pptx, txt)
        title: Document title
        template: Template style (default, quiz, report)
        filename: Custom filename (optional)
    
    Returns:
        String with generation result and file path
    """
    try:
        config = DocumentConfig(
            content=content,
            document_type=document_type,
            title=title,
            template=template
        )
        
        result = document_generator.generate_document(config)
        
        if result["success"]:
            return f"""✅ Document generated successfully!

📄 File: {result['filename']}
📁 Path: {result['relative_path']}
📊 Type: {result['document_type'].upper()}
📏 Size: {result['size_bytes']} bytes
📝 Title: {result['title']}

The document has been saved and is ready for use."""

        else:
            return f"❌ Failed to generate document: {result['error']}"
            
    except Exception as e:
        return f"❌ Error in document generation: {str(e)}"


@tool
def quiz_document_tool(quiz_content: str, quiz_params: str) -> str:
    """
    Generate a quiz document with specialized formatting.
    
    Args:
        quiz_content: The quiz questions and content
        quiz_params: JSON string containing quiz parameters
    
    Returns:
        String with generation result and file path
    """
    try:
        # Parse quiz parameters
        params = json.loads(quiz_params) if isinstance(quiz_params, str) else quiz_params
        
        result = document_generator.generate_quiz_document(quiz_content, params)
        
        if result["success"]:
            return f"""📝 Quiz document generated successfully!

🎯 Quiz: {result['title']}
📄 File: {result['filename']}
📁 Path: {result['relative_path']}
📊 Format: {result['document_type'].upper()}
📏 Size: {result['size_bytes']} bytes

Your quiz is ready for distribution!"""

        else:
            return f"❌ Failed to generate quiz document: {result['error']}"
            
    except Exception as e:
        return f"❌ Error in quiz document generation: {str(e)}"


# Export the main classes and tools
__all__ = [
    'EnhancedDocumentGenerator',
    'DocumentConfig', 
    'DocumentTemplate',
    'enhanced_document_tool',
    'quiz_document_tool',
    'document_generator'
]
