"""
Document Export Tool: A LangChain tool for exporting content to various document formats.

This tool provides document export functionality with proper formatting for:
- PDF: Formatted with title alignment, subtitle highlighting, and bold text
- TXT: Plain text export with basic formatting

Integrates with existing enhanced_document_generator and doc_writer utilities.
"""

import os
from typing import Optional, Dict, Any, List
from pathlib import Path
from datetime import datetime
from langchain_core.tools import tool
from pydantic import BaseModel, Field
from langchain_tools.document_exporter.enhanced_document_generator import document_generator, DocumentConfig
from langchain_tools.document_exporter.doc_writer import DocumentWriter

# Additional imports for PPTX and AI integration
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.enum.text import PP_ALIGN
    from pptx.dml.color import RGBColor
    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False

try:
    from langchain_google_genai import ChatGoogleGenerativeAI
    import requests
    import json
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


class DocumentExportInput(BaseModel):
    """Input schema for Document Export Tool"""
    content: str = Field(..., description="The actual content to export")
    file_type: str = Field(..., description="File type to export: 'pdf', 'txt', or 'pptx'")
    title: str = Field(..., description="Title of the document")

class DocumentExportTool:
    """
    A tool for exporting content to formatted documents.
    
    Supports:
    - PDF: Professional formatting with title alignment, subtitle highlighting, and bold text
    - TXT: Plain text export with basic structure
    - PPTX: AI-powered PowerPoint presentations with intelligent slide layout and image integration
    """
    
    def __init__(self, base_output_dir: str = "generated_documents"):
        self.base_output_dir = Path(base_output_dir)
        self.base_output_dir.mkdir(exist_ok=True)
        
        # Initialize Gemini for AI-powered slide generation
        self.gemini_llm = None
        if GEMINI_AVAILABLE:
            try:
                api_key = os.getenv("GEMINI_API_KEY")
                if api_key:
                    self.gemini_llm = ChatGoogleGenerativeAI(
                        model="gemini-2.5-pro",
                        google_api_key=api_key,
                        temperature=0.3
                    )
            except Exception as e:
                print(f"Warning: Could not initialize Gemini API: {e}")
    
    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename to remove invalid characters"""
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, '_')
        return filename[:50]  # Limit length
    
    def _generate_filename(self, title: str, file_type: str) -> str:
        """Generate appropriate filename"""
        
        if title and title.strip():
            base_name = self._sanitize_filename(title)
        else:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            base_name = f"document_{timestamp}"
        
        return f"{base_name}.{file_type}"
    
    def _format_content_for_pdf(self, content: str, title: str, subtitle: Optional[str] = None, 
                               author: Optional[str] = None) -> str:
        """
        Format content for PDF with proper styling.
        
        This function prepares content with:
        - Centered title (bold and larger)
        - Highlighted subtitle (if provided)
        - Author information
        - Properly structured content with markdown-like formatting
        """
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        # Build formatted content
        formatted_parts = []
        
        # Title (centered and bold)
        formatted_parts.append(f"# {title.upper()}")
        formatted_parts.append("")  # Empty line
        
        # Subtitle (if provided)
        if subtitle and subtitle.strip():
            formatted_parts.append(f"## {subtitle}")
            formatted_parts.append("")
        
        # Author and date info
        if author:
            formatted_parts.append(f"**Author:** {author}")
        formatted_parts.append(f"**Date:** {timestamp}")
        formatted_parts.append("")
        formatted_parts.append("---")  # Separator
        formatted_parts.append("")
        
        # Main content
        formatted_parts.append(content)
        
        # Footer
        formatted_parts.append("")
        formatted_parts.append("---")
        formatted_parts.append("*Generated by SME Document Export Tool*")
        
        return "\n".join(formatted_parts)
    
    def _format_content_for_txt(self, content: str, title: str, subtitle: Optional[str] = None,
                               author: Optional[str] = None) -> str:
        """
        Format content for TXT with basic structure.
        
        Simple text formatting with clear sections.
        """
        timestamp = datetime.now().strftime("%B %d, %Y")
        
        # Build formatted content
        formatted_parts = []
        
        # Title
        title_line = title.upper()
        formatted_parts.append(title_line)
        formatted_parts.append("=" * len(title_line))  # Underline with equals
        formatted_parts.append("")
        
        # Subtitle
        if subtitle and subtitle.strip():
            formatted_parts.append(subtitle)
            formatted_parts.append("-" * len(subtitle))  # Underline with dashes
            formatted_parts.append("")
        
        # Author and date
        if author:
            formatted_parts.append(f"Author: {author}")
        formatted_parts.append(f"Date: {timestamp}")
        formatted_parts.append("")
        formatted_parts.append("-" * 50)  # Separator
        formatted_parts.append("")
        
        # Main content
        formatted_parts.append(content)
        
        # Footer
        formatted_parts.append("")
        formatted_parts.append("-" * 50)
        formatted_parts.append("Generated by SME Document Export Tool")
        
        return "\n".join(formatted_parts)
    
    def _analyze_content_for_slides(self, content: str, title: str) -> List[Dict[str, Any]]:
        """
        Use Gemini AI to analyze content and create intelligent slide breakdown.
        
        Returns a list of slide dictionaries with title, content, and image suggestions.
        """
        if not self.gemini_llm:
            # Fallback to simple slide breakdown
            return self._simple_slide_breakdown(content, title)
        
        try:
            prompt = f"""
Analyze the following content and create an intelligent PowerPoint presentation structure.
Title: {title}
Content: {content}

Please provide a JSON response with the following structure:
{{
    "slides": [
        {{
            "slide_number": 1,
            "slide_title": "Title Slide",
            "slide_type": "title",
            "content": "Main title and subtitle",
            "bullet_points": [],
            "image_keywords": ["presentation", "professional"],
            "layout_suggestion": "title_layout"
        }},
        {{
            "slide_number": 2,
            "slide_title": "Introduction",
            "slide_type": "content",
            "content": "Brief introduction text",
            "bullet_points": ["Point 1", "Point 2"],
            "image_keywords": ["introduction", "overview"],
            "layout_suggestion": "content_with_image"
        }}
    ]
}}

Guidelines:
1. Create 5-8 slides maximum
2. Include title slide
3. Break content into logical sections
4. Suggest relevant image keywords for each slide
5. Identify slide types: "title", "content", "bullet_points", "conclusion"
6. Suggest appropriate layouts
7. Keep slide content concise and engaging

Respond with valid JSON only.
"""

            response = self.gemini_llm.invoke(prompt)
            
            # Parse the JSON response
            try:
                slide_data = json.loads(response.content)
                return slide_data.get("slides", [])
            except json.JSONDecodeError:
                print("Warning: Could not parse Gemini response, using fallback")
                return self._simple_slide_breakdown(content, title)
                
        except Exception as e:
            print(f"Warning: Gemini analysis failed: {e}, using fallback")
            return self._simple_slide_breakdown(content, title)
    
    def _simple_slide_breakdown(self, content: str, title: str) -> List[Dict[str, Any]]:
        """
        Fallback method for simple slide breakdown without AI.
        """
        slides = []
        
        # Title slide
        slides.append({
            "slide_number": 1,
            "slide_title": title,
            "slide_type": "title",
            "content": title,
            "bullet_points": [],
            "image_keywords": ["presentation", "professional"],
            "layout_suggestion": "title_layout"
        })
        
        # Split content into paragraphs and create slides
        paragraphs = [p.strip() for p in content.split('\n\n') if p.strip()]
        
        for i, paragraph in enumerate(paragraphs[:6], 2):  # Max 6 content slides
            # Extract title from first line if it looks like a heading
            lines = paragraph.split('\n')
            slide_title = f"Slide {i}"
            slide_content = paragraph
            
            if len(lines) > 1 and len(lines[0]) < 100:
                slide_title = lines[0].strip('# ').strip()
                slide_content = '\n'.join(lines[1:])
            
            # Create bullet points if content has list structure
            bullet_points = []
            if '•' in slide_content or '-' in slide_content or any(line.strip().startswith(('1.', '2.', '3.')) for line in lines):
                bullet_points = [line.strip('•- ').strip() for line in lines if line.strip() and not line.strip().startswith('#')]
                bullet_points = [bp for bp in bullet_points if len(bp) > 3][:5]  # Max 5 bullets
                
            slides.append({
                "slide_number": i,
                "slide_title": slide_title,
                "slide_type": "content" if not bullet_points else "bullet_points",
                "content": slide_content if not bullet_points else "",
                "bullet_points": bullet_points,
                "image_keywords": ["relevant", "topic"],
                "layout_suggestion": "content_with_image" if not bullet_points else "bullet_layout"
            })
        
        return slides
    
    def _search_and_add_placeholder_image(self, slide, keywords: List[str]):
        """
        Add placeholder for images based on keywords.
        In a production environment, this would integrate with image search APIs.
        """
        # For now, we'll add a text placeholder
        # In production, you could integrate with:
        # - Unsplash API
        # - Pexels API  
        # - Google Custom Search API
        # - Stock photo services
        
        placeholder_text = f"[IMAGE: {', '.join(keywords)}]"
        return placeholder_text
    
    def _create_pptx_presentation(self, slides_data: List[Dict[str, Any]], title: str) -> str:
        """
        Create a PowerPoint presentation from slide data.
        """
        if not PPTX_AVAILABLE:
            raise ImportError("python-pptx is required for PowerPoint generation. Install with: pip install python-pptx")
        
        # Create presentation
        prs = Presentation()
        
        for slide_data in slides_data:
            if slide_data["slide_type"] == "title":
                # Title slide
                slide_layout = prs.slide_layouts[0]  # Title layout
                slide = prs.slides.add_slide(slide_layout)
                
                title_placeholder = slide.shapes.title
                title_placeholder.text = slide_data["slide_title"]
                
                if slide.placeholders[1]:  # Subtitle placeholder
                    subtitle_placeholder = slide.placeholders[1]
                    subtitle_placeholder.text = f"Generated on {datetime.now().strftime('%B %d, %Y')}"
                    
            elif slide_data["slide_type"] == "bullet_points":
                # Bullet points slide
                slide_layout = prs.slide_layouts[1]  # Title and Content layout
                slide = prs.slides.add_slide(slide_layout)
                
                title_placeholder = slide.shapes.title
                title_placeholder.text = slide_data["slide_title"]
                
                content_placeholder = slide.placeholders[1]
                text_frame = content_placeholder.text_frame
                text_frame.clear()
                
                for bullet_point in slide_data["bullet_points"]:
                    p = text_frame.add_paragraph()
                    p.text = bullet_point
                    p.level = 0
                    
            else:
                # Content slide
                slide_layout = prs.slide_layouts[5]  # Blank layout for custom content
                slide = prs.slides.add_slide(slide_layout)
                
                # Add title
                title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.5), Inches(9), Inches(1))
                title_frame = title_shape.text_frame
                title_para = title_frame.paragraphs[0]
                title_para.text = slide_data["slide_title"]
                title_para.font.size = Pt(32)
                title_para.font.bold = True
                
                # Add content
                content_shape = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(9), Inches(5))
                content_frame = content_shape.text_frame
                content_para = content_frame.paragraphs[0]
                content_para.text = slide_data["content"]
                content_para.font.size = Pt(18)
                
                # Add image placeholder
                if slide_data.get("image_keywords"):
                    image_placeholder = self._search_and_add_placeholder_image(slide, slide_data["image_keywords"])
                    img_shape = slide.shapes.add_textbox(Inches(7), Inches(3), Inches(2.5), Inches(2))
                    img_frame = img_shape.text_frame
                    img_para = img_frame.paragraphs[0]
                    img_para.text = image_placeholder
                    img_para.font.size = Pt(12)
                    img_para.font.italic = True
        
        return prs
    
    def export_document(self, content: str, file_type: str, title: str) -> Dict[str, Any]:
        """
        Export content to the specified document format.
        
        Args:
            content: The actual content to export
            file_type: File type ('pdf' or 'txt')
            title: Document title
        
        Returns:
            Dictionary with export results
        """
        try:
            # Validate file type
            file_type = file_type.lower().strip()
            if file_type not in ['pdf', 'txt', 'pptx']:
                return {
                    "success": False,
                    "error": f"Unsupported file type: {file_type}. Only 'pdf', 'txt', and 'pptx' are supported."
                }
            
            # Determine output directory
           
            final_output_dir = self.base_output_dir
            final_output_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate filename
            file_name = self._generate_filename(title, file_type)
            output_path = final_output_dir / file_name
            
            # Format content based on file type
            if file_type == 'pdf':
                formatted_content = self._format_content_for_pdf(content, title)
                
                template = "default"
                if 'quiz' in title.lower():
                    template = "quiz"

                config = DocumentConfig(
                    content=formatted_content,
                    document_type="pdf",
                    title=title,
                    template=template
                )
                
                result = document_generator.generate_document(config)
                
                if result["success"]:
                    return {
                        "success": True,
                        "file_path": result["file_path"],
                        "file_type": file_type,
                        "title": title,
                        "message": f"PDF document '{title}' exported successfully"
                    }
                else:
                    return {
                        "success": False,
                        "error": f"Failed to generate PDF: {result.get('error', 'Unknown error')}"
                    }
            
            elif file_type == 'txt':
                formatted_content = self._format_content_for_txt(content, title)
                
                DocumentWriter._write_txt(formatted_content, str(output_path))
                
                return {
                    "success": True,
                    "file_path": str(output_path),
                    "file_type": file_type,
                    "title": title,
                    "message": f"TXT document '{title}' exported successfully"
                }
            
            elif file_type == 'pptx':
                # AI-powered PowerPoint generation
                print(f"🤖 Analyzing content for intelligent slide creation...")
                slides_data = self._analyze_content_for_slides(content, title)
                print(f"📊 Created {len(slides_data)} slides")
                
                # Create PowerPoint presentation
                prs = self._create_pptx_presentation(slides_data, title)
                
                # Save the presentation
                prs.save(str(output_path))
                
                # Create summary of slides created
                slide_summary = []
                for slide in slides_data:
                    slide_summary.append(f"Slide {slide['slide_number']}: {slide['slide_title']} ({slide['slide_type']})")
                
                return {
                    "success": True,
                    "file_path": str(output_path),
                    "file_type": file_type,
                    "title": title,
                    "message": f"PPTX presentation '{title}' exported successfully",
                    "slide_summary": slide_summary,
                    "total_slides": len(slides_data)
                }
                
        except Exception as e:
            return {
                "success": False,
                "error": f"Export failed: {str(e)}"
            }


# Create global instance
export_tool = DocumentExportTool()


@tool
def document_export_tool(
    content: str,
    file_type: str,
    title: str
) -> str:
    """
    LangChain tool for exporting content to formatted documents.
    This is a StructuredTool object - use .invoke() method to call it.
    
    Args:
        content: The actual content to export
        file_type: File type to export ('pdf', 'txt', or 'pptx')
        title: Title of the document (will be aligned and formatted properly)
    
    Returns:
        String with export status and file path
        
    Examples:
        # Export to PDF
        document_export_tool.invoke({
            "content": "This is the main content...",
            "file_type": "pdf",
            "title": "Constitutional Rights Analysis"
        })
        
        # Export to TXT
        document_export_tool.invoke({
            "content": "Simple text content...",
            "file_type": "txt", 
            "title": "Meeting Notes"
        })
        
        # Export to PowerPoint (AI-powered)
        document_export_tool.invoke({
            "content": "Detailed content about constitutional rights...",
            "file_type": "pptx",
            "title": "Constitutional Rights Presentation"
        })
    """
    try:
        result = export_tool.export_document(
            content=content,
            file_type=file_type,
            title=title
        )
        
        if result["success"]:
            message = f"""✅ {result['message']}

📁 File saved at: {result['file_path']}
📋 Document type: {result['file_type'].upper()}
📝 Title: {result['title']}

The document has been exported with proper formatting:
{f'- Title aligned and highlighted' if file_type.lower() == 'pdf' else '- Title properly formatted'}"""

            # Add PPTX-specific information
            if file_type.lower() == 'pptx' and 'slide_summary' in result:
                message += f"""

🎯 PowerPoint Details:
📊 Total slides: {result.get('total_slides', 0)}
📋 Slide breakdown:"""
                for slide_info in result.get('slide_summary', []):
                    message += f"\n   • {slide_info}"
                
                # Check if AI was used (via export_tool global instance)
                if export_tool.gemini_llm:
                    message += "\n\n🤖 Generated with AI-powered content analysis and slide optimization"
                else:
                    message += "\n\n📝 Generated with automatic content breakdown"
            
            return message
        else:
            return f"❌ Export failed: {result['error']}"
            
    except Exception as e:
        return f"❌ Unexpected error during export: {str(e)}"


# Export for easy import
__all__ = ['DocumentExportTool', 'document_export_tool', 'export_tool', 'DocumentExportInput']
